before_install:
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
  - "sudo apt-get install graphviz 2>&1 | tail -n 2"
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/plantuml.jar
  - hg clone -r 8.6.7 https://asciidoc.googlecode.com/hg/ asciidoc-8.6.7
before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.3.tar.gz -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.0.3/bin/
language: java
script:
  - java -version
  - javac -version
  - python -V
  - phantomjs -v
  - python asciidoc-8.6.7/asciidoc.py --version
  - dot -V
  - ls -alF
  - casperjs --version
  - cd sprint_5
  - javac -cp .:./bin:./tools/junit.jar -d ./bin ./src/controler/MakeOPTIweb.java ./src/model/*.java
  - java -jar ../plantuml.jar -Tpng -o srcdoc/images srcdoc/diag0.puml
  - python ../asciidoc-8.6.7/asciidoc.py -a data-uri -o srcdoc/presentationFinale.html srcdoc/presentationFinale.txt
  - python ../asciidoc-8.6.7/asciidoc.py -a data-uri -o srcdoc/documentation_utilisateur_MakeOptiWeb.html srcdoc/documentation_utilisateur.adoc
  - python ../asciidoc-8.6.7/asciidoc.py -a data-uri -o srcdoc/documentation_technique_MakeOptiWeb.html srcdoc/documentation_technique.adoc
  - ls -alF srcdoc
  - cd bin
  - java -cp .:../../junit.jar:./controler controler.MakeOPTIweb
  - java -cp .:../../junit.jar:./controler model.MakeOPTIwebTest
  - cd ../OPTIweb/test
  - cp OPTIweb.html /tmp/OPTIweb.html
  - casperjs test casperAccueil.js
  - casperjs test casperCredits.js
  - casperjs test casperProjets.js
  - casperjs test casperSujets.js
  - casperjs test casperEtudiants.js
  - casperjs test casperIntervenants.js
